INSERT INTO [DataVaultStaging].[stg].[Customers]
 (      [CustomerID]
       ,[CompanyName]
       ,[ContactName]
       ,[ContactTitle]
       ,[Address]
       ,[City]
       ,[Region]
       ,[PostalCode]
       ,[Country]
       ,[Phone]
       ,[Fax]
       ,[RecordSource]
       ,[LoadDate]
 )
 SELECT [CustomerID]
       ,[CompanyName]
       ,[ContactName]
       ,[ContactTitle]
       ,[Address]
       ,[City]
       ,[Region]
       ,[PostalCode]
       ,[Country]
       ,[Phone]
       ,[Fax]
      ,'Northwind_Sqldb' AS [RecordSource]
      ,CAST(GETDATE() AS DATE) AS [LoadDate]
 FROM master.[dbo].[Customers]
 ; 